apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-postgres-config
  namespace: default
data:
  postgres_db: ecommerce
  postgres_user: admin
  postgres_password: admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-postgres
spec:
  selector:
    matchLabels:
      app: backend-postgres
  template:
    metadata:
      labels:
        app: backend-postgres
    spec:
      volumes:
        - name: backend-postgres-storage
          persistentVolumeClaim:
            claimName: files-postgres-pv-claim
      containers:
        - image: postgres
          name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: files-postgres-config
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: files-postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: files-postgres-config
                  key: postgres_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pfiles-gdata
          ports:
            - containerPort: 5432
              name: backend-pg
          volumeMounts:
            - name: backend-postgres-storage
              mountPath: /var/lib/postgresql/backend-data
---
apiVersion: v1
kind: Service
metadata:
  name: backend-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: backend-postgres
