apiVersion: v1
kind: Secret
metadata:
  name: secret-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIzMjQyNTAxNjgwNjcuZGtyLmVjci5ldS13ZXN0LTEuYW1hem9uYXdzLmNvbSI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIKfQ==